# Dependencies
markdown:         redcarpet
highlighter:      pygments
github: [Repository metadata]

# Permalinks
permalink:        /:categories/:year/:title
relative_permalinks: true

# Setup
title:            guaka
tagline:          life is too important to be taken seriously
description:      life is too important to be taken seriously
url:              https://guaka.github.io
baseurl:         /

author:		Kasper Souren
url:            /

paginate:         5

# Custom vars
# version:          2.1.0

# github:	
#  repo:           https://github.com/guaka/guaka.github.io

# Site owner
owner:
  name: Kasper Souren
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: guaka
  facebook: #username
  github: guakak
  stackexchange: http://stackoverflow.com/users/1245190/kasper-souren
  linkedin: #username
  instagram: #username
  flickr: guaka
  tumblr: #username
  google:
    plus: +KasperSouren
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:


